### ISSUE TITLE
macos15.0 安装moonpalace后，运行二进制文件失败

### ISSUE THREAD

**Issue by hongxiangWang** [MoonshotAI/moonpalace#4]
使用go语言安装
`go install github.com/MoonshotAI/moonpalace@latest`
编译出的二进制文件运行失败
<img width="569" alt="image" src="https://github.com/user-attachments/assets/925abbb2-54ba-41c5-b774-8cb2082414b0">

补充：芯片Apple M1

**Comment by x5iu** [comment]
编译后运行以下命令

```shell
$ /Users/wanghongxiang/go/bin/moonpalace help
```

能看到帮助信息么🤔

**Comment by x5iu** [comment]
推测可能是 Apple 安全策略导致运行失败，可以尝试以下做法：

1. 打开 `/Users/wanghongxiang/go/bin/moonpalace` 目录；
2. 右键点击 `moonpalace` 文件，并选择菜单中的第一个选项“打开”；
3. 在弹出的菜单中，选择“打开”；
4. 在终端中重新运行：
 ```shell
 $ chmod +x /Users/wanghongxiang/go/bin/moonpalace
 $ /Users/wanghongxiang/go/bin/moonpalace help
 ```
看是否能正确输出

**Comment by x5iu** [comment]
确实有点奇怪，zsh 直接提示 killed，但是却没写错误原因，导致我只能尽可能猜测报错的原因。

如果使用 `go install` 安装始终无法成功，可以考虑从 [Release](https://github.com/MoonshotAI/moonpalace/releases) 下载编译好的二进制文件。

*如果二进制文件提示安全问题，可以从右键菜单中选择“打开”，打开一次后即可在命令行中调用。*

**Comment by x5iu** [comment]
源码运行正常的话，直接从源码编译安装吧，在 `moonpalace` 目录执行

```shell
$ go install
```

但是目前确实不太清楚为什么会出现这样的问题😂
